name: CI workflow
on: [push, pull_request]

jobs:
  sbt-build:
    uses: ./.github/workflows/sbt-build.yml

  docker:
    uses: ./.github/workflows/docker.yml
    needs: sbt-build
    with:
      jar-artifact: ${{ needs.sbt-build.outputs.jar-artifact }}
      tags: ghcr.io/ripe-ncc/rpki-publication-server:unstable
      push: ${{ github.ref == 'refs/heads/main' }}
