name: docker
on:
  workflow_call:
    inputs:
      jar-artifact:
        description: "Name of the executable JAR artifact to download."
        type: string
        required: true
      push:
        description: "Whether to push the image."
        type: boolean
        required: true
        default: false
      tag:
        description: "Image tag"
        type: string
        required: true
    secrets:
      docker_hub_username:
        required: true
      docker_hub_access_token:
        required: true

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: checkout sources
        uses: actions/checkout@v3

      - name: Fetch jar
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.jar-artifact }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.docker_hub_username }}
          password: ${{ secrets.docker_hub_access_token }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build_publication_server
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: ${{ inputs.push }}
          tags: ripencc/rpki-publication-server:${{ inputs.tag }}
          labels: "org.label-schema.vcs-ref=${{ github.sha }}"
          build-args: |
            PUBLICATION_SERVER_JAR=./rpki-publication-server.jar

      - name: Image digest
        run: echo ${{ steps.docker_build_publication_server.outputs.digest }}
